#include "resource_database.h"

const std::map<ResourceName, ResourceBonus> data = {
    // Stratégique
    {ResourceName::Horse,
     {ResourceName::Horse, ResourceType::Strategic, 0, 1, 1, 0, 0}},
    {ResourceName::Iron,
     {ResourceName::Iron, ResourceType::Strategic, 0, 1, 0, 0, 0}},
    {ResourceName::Copper,
     {ResourceName::Copper, ResourceType::Strategic, 0, 1, 0, 0, 0}},
    {ResourceName::Coal,
     {ResourceName::Coal, ResourceType::Strategic, 0, 2, 0, 0, 0}},
    {ResourceName::Oil,
     {ResourceName::Oil, ResourceType::Strategic, 0, 1, 2, 0, 0}},
    {ResourceName::Uranium,
     {ResourceName::Uranium, ResourceType::Strategic, 0, 0, 3, 0, 0}},
    {ResourceName::Aluminum,
     {ResourceName::Aluminum, ResourceType::Strategic, 0, 1, 0, 0, 0}},

    // Santé
    {ResourceName::Corn,
     {ResourceName::Corn, ResourceType::Health, 1, 0, 0, 0, 1}},
    {ResourceName::Rice,
     {ResourceName::Rice, ResourceType::Health, 1, 0, 0, 0, 1}},
    {ResourceName::Wheat,
     {ResourceName::Wheat, ResourceType::Health, 1, 0, 0, 0, 1}},
    {ResourceName::Banana,
     {ResourceName::Banana, ResourceType::Health, 1, 0, 0, 0, 1}},
    {ResourceName::Deer,
     {ResourceName::Deer, ResourceType::Health, 1, 0, 0, 0, 1}},
    {ResourceName::Pig,
     {ResourceName::Pig, ResourceType::Health, 1, 0, 0, 0, 1}},
    {ResourceName::Cow,
     {ResourceName::Cow, ResourceType::Health, 1, 0, 0, 0, 1}},
    {ResourceName::Sheep,
     {ResourceName::Sheep, ResourceType::Health, 1, 0, 0, 0, 1}},
    {ResourceName::Fish,
     {ResourceName::Fish, ResourceType::Health, 1, 0, 0, 0, 1}},
    {ResourceName::Clam,
     {ResourceName::Clam, ResourceType::Health, 1, 0, 0, 0, 1}},
    {ResourceName::Crab,
     {ResourceName::Crab, ResourceType::Health, 1, 0, 0, 0, 1}},

    // Luxe
    {ResourceName::Gold,
     {ResourceName::Gold, ResourceType::Luxury, 0, 0, 3, 1, 0}},
    {ResourceName::Silver,
     {ResourceName::Silver, ResourceType::Luxury, 0, 0, 2, 1, 0}},
    {ResourceName::Gems,
     {ResourceName::Gems, ResourceType::Luxury, 0, 0, 2, 1, 0}},
    {ResourceName::Ivory,
     {ResourceName::Ivory, ResourceType::Luxury, 0, 1, 0, 1, 0}},
    {ResourceName::Fur,
     {ResourceName::Fur, ResourceType::Luxury, 0, 0, 1, 1, 0}},
    {ResourceName::Dye,
     {ResourceName::Dye, ResourceType::Luxury, 0, 0, 1, 1, 0}},
    {ResourceName::Incense,
     {ResourceName::Incense, ResourceType::Luxury, 0, 0, 1, 1, 0}},
    {ResourceName::Silk,
     {ResourceName::Silk, ResourceType::Luxury, 0, 0, 1, 1, 0}},
    {ResourceName::Sugar,
     {ResourceName::Sugar, ResourceType::Luxury, 0, 0, 1, 1, 0}},
    {ResourceName::Spices,
     {ResourceName::Spices, ResourceType::Luxury, 0, 0, 1, 1, 0}},
    {ResourceName::Wine,
     {ResourceName::Wine, ResourceType::Luxury, 0, 0, 1, 1, 0}},
    {ResourceName::Whale,
     {ResourceName::Whale, ResourceType::Luxury, 0, 1, 1, 1, 0}}};
