#include "type.h"

#include <map>

const std::map<Country, Color> COUNTRY_COLOR = {
    {Country::Neutral, Color::Transparent},
    {Country::France, Color::RoyalBlue},
    {Country::Germany, Color::DarkGrey},
    {Country::UnitedKingdom, Color::Crimson},
    {Country::Russia, Color::White},
    {Country::Egypt, Color::GoldenRod},
    {Country::Switzerland, Color::BrightRed},
    {Country::Japan, Color::CherryBlossom},
    {Country::Spain, Color::Orange},
    {Country::Italy, Color::Emerald},
    {Country::UnitedStates, Color::NavyBlue}};

const std::map<TechnologyName, std::string> TECHNOLOGY_STRING_NAME = {
    {TechnologyName::AdvancedFlight, "Advanced Flight"},
    {TechnologyName::Aesthetics, "Aesthetics"},
    {TechnologyName::Agriculture, "Agriculture"},
    {TechnologyName::Alphabet, "Alphabet"},
    {TechnologyName::AnimalHusbandry, "Animal Husbandry"},
    {TechnologyName::Archery, "Archery"},
    {TechnologyName::Artillery, "Artillery"},
    {TechnologyName::AssemblyLine, "Assembly Line"},
    {TechnologyName::Astronomy, "Astronomy"},
    {TechnologyName::Banking, "Banking"},
    {TechnologyName::Biology, "Biology"},
    {TechnologyName::BronzeWorking, "Bronze Working"},
    {TechnologyName::Calendar, "Calendar"},
    {TechnologyName::Chemistry, "Chemistry"},
    {TechnologyName::CivilService, "Civil Service"},
    {TechnologyName::CodeOfLaws, "Code of Laws"},
    {TechnologyName::Combustion, "Combustion"},
    {TechnologyName::Communism, "Communism"},
    {TechnologyName::Compass, "Compass"},
    {TechnologyName::Composites, "Composites"},
    {TechnologyName::Computers, "Computers"},
    {TechnologyName::Constitution, "Constitution"},
    {TechnologyName::Construction, "Construction"},
    {TechnologyName::Corporation, "Corporation"},
    {TechnologyName::Currency, "Currency"},
    {TechnologyName::Democracy, "Democracy"},
    {TechnologyName::DivineRight, "Divine Right"},
    {TechnologyName::Drama, "Drama"},
    {TechnologyName::Ecology, "Ecology"},
    {TechnologyName::Economics, "Economics"},
    {TechnologyName::Education, "Education"},
    {TechnologyName::Electricity, "Electricity"},
    {TechnologyName::Engineering, "Engineering"},
    {TechnologyName::Fascism, "Fascism"},
    {TechnologyName::Feudalism, "Feudalism"},
    {TechnologyName::FiberOptics, "Fiber Optics"},
    {TechnologyName::Fishing, "Fishing"},
    {TechnologyName::Fission, "Fission"},
    {TechnologyName::Flight, "Flight"},
    {TechnologyName::Fusion, "Fusion"},
    {TechnologyName::FutureTech, "Future Tech"},
    {TechnologyName::Genetics, "Genetics"},
    {TechnologyName::Guilds, "Guilds"},
    {TechnologyName::Gunpowder, "Gunpowder"},
    {TechnologyName::HorsebackRiding, "Horseback Riding"},
    {TechnologyName::Hunting, "Hunting"},
    {TechnologyName::Industrialism, "Industrialism"},
    {TechnologyName::IronWorking, "Iron Working"},
    {TechnologyName::Laser, "Laser"},
    {TechnologyName::Liberalism, "Liberalism"},
    {TechnologyName::Literature, "Literature"},
    {TechnologyName::Machinery, "Machinery"},
    {TechnologyName::Masonry, "Masonry"},
    {TechnologyName::MassMedia, "Mass Media"},
    {TechnologyName::Mathematics, "Mathematics"},
    {TechnologyName::Medicine, "Medicine"},
    {TechnologyName::Meditation, "Meditation"},
    {TechnologyName::MetalCasting, "Metal Casting"},
    {TechnologyName::MilitaryScience, "Military Science"},
    {TechnologyName::MilitaryTradition, "Military Tradition"},
    {TechnologyName::Mining, "Mining"},
    {TechnologyName::Monarchy, "Monarchy"},
    {TechnologyName::Monotheism, "Monotheism"},
    {TechnologyName::Music, "Music"},
    {TechnologyName::Mysticism, "Mysticism"},
    {TechnologyName::Nationalism, "Nationalism"},
    {TechnologyName::Optics, "Optics"},
    {TechnologyName::Paper, "Paper"},
    {TechnologyName::Philosophy, "Philosophy"},
    {TechnologyName::Physics, "Physics"},
    {TechnologyName::Plastics, "Plastics"},
    {TechnologyName::Polytheism, "Polytheism"},
    {TechnologyName::Pottery, "Pottery"},
    {TechnologyName::Priesthood, "Priesthood"},
    {TechnologyName::PrintingPress, "Printing Press"},
    {TechnologyName::Radio, "Radio"},
    {TechnologyName::Railroad, "Railroad"},
    {TechnologyName::Refrigeration, "Refrigeration"},
    {TechnologyName::ReplaceableParts, "Replaceable Parts"},
    {TechnologyName::Rifling, "Rifling"},
    {TechnologyName::Robotics, "Robotics"},
    {TechnologyName::Rocketry, "Rocketry"},
    {TechnologyName::Sailing, "Sailing"},
    {TechnologyName::Satellites, "Satellites"},
    {TechnologyName::ScientificMethod, "Scientific Method"},
    {TechnologyName::Stealth, "Stealth"},
    {TechnologyName::SteamPower, "Steam Power"},
    {TechnologyName::Steel, "Steel"},
    {TechnologyName::Superconductors, "Superconductors"},
    {TechnologyName::TheWheel, "The Wheel"},
    {TechnologyName::Theology, "Theology"},
    {TechnologyName::Writing, "Writing"}};

const std::map<UnitName, UnitStats> UNIT_STATS = {
    // --- Civil ---
    {UnitName::Settler, {1, 0, 2, 100}},
    {UnitName::Worker, {1, 0, 2, 60}},
    {UnitName::WorkBoat, {1, 0, 2, 30}},

    // --- Melee ---
    {UnitName::Warrior, {100, 2, 1, 15}},
    {UnitName::Swordsman, {100, 6, 1, 40}},
    {UnitName::Axeman, {100, 5, 1, 35}},
    {UnitName::Maceman, {100, 8, 1, 70}},
    {UnitName::Pikeman, {100, 6, 1, 60}},

    // --- Gunpowder ---
    {UnitName::Musketman, {100, 9, 1, 80}},
    {UnitName::Rifleman, {100, 14, 1, 110}},
    {UnitName::Grenadier, {100, 12, 1, 100}},
    {UnitName::AntiTank, {100, 14, 1, 120}},
    {UnitName::Infantry, {100, 20, 1, 140}},
    {UnitName::SAMInfantry, {100, 18, 1, 150}},
    {UnitName::MobileSAM, {100, 22, 2, 220}},
    {UnitName::Marine, {100, 24, 1, 160}},
    {UnitName::NavySEAL, {100, 24, 1, 160}},
    {UnitName::Paratrooper, {100, 24, 1, 160}},
    {UnitName::MechanizedInfantry, {100, 32, 2, 200}},

    // --- Archery ---
    {UnitName::Archer, {100, 3, 1, 25}},
    {UnitName::Longbowman, {100, 6, 1, 50}},
    {UnitName::Crossbowman, {100, 6, 1, 60}},

    // --- Mounted ---
    {UnitName::Chariot, {100, 4, 2, 30}},
    {UnitName::HorseArcher, {100, 6, 2, 50}},
    {UnitName::Cuirassier, {100, 12, 2, 100}},
    {UnitName::Cavalry, {100, 15, 2, 120}},
    {UnitName::WarElephant, {100, 8, 1, 60}},
    {UnitName::BallistaElephant, {100, 8, 1, 60}},

    // --- Armored & Helicopter ---
    {UnitName::Tank, {100, 28, 2, 180}},
    {UnitName::ModernArmor, {100, 40, 2, 240}},
    {UnitName::Gunship, {100, 24, 4, 160}},

    // --- Siege ---
    {UnitName::Catapult, {100, 5, 1, 50}},
    {UnitName::Trebuchet, {100, 4, 1, 80}},
    {UnitName::Cannon, {100, 12, 1, 100}},
    {UnitName::MachineGun, {100, 18, 1, 125}},
    {UnitName::Artillery, {100, 18, 1, 150}},
    {UnitName::MobileArtillery, {100, 26, 2, 200}},

    // --- Naval ---
    {UnitName::Galley, {100, 2, 2, 50}},
    {UnitName::Trireme, {100, 2, 2, 50}},
    {UnitName::Caravel, {100, 3, 3, 60}},
    {UnitName::Galleon, {100, 4, 4, 80}},
    {UnitName::Privateer, {100, 6, 4, 80}},
    {UnitName::Frigate, {100, 8, 4, 90}},
    {UnitName::ShipOfTheLine, {100, 8, 3, 120}},
    {UnitName::Ironclad, {100, 12, 2, 100}},
    {UnitName::Transport, {100, 16, 5, 125}},
    {UnitName::Destroyer, {100, 30, 8, 200}},
    {UnitName::Battleship, {100, 40, 6, 225}},
    {UnitName::MissileCruiser, {100, 40, 7, 260}},
    {UnitName::StealthDestroyer, {100, 30, 8, 220}},
    {UnitName::Submarine, {100, 24, 6, 150}},
    {UnitName::AttackSubmarine, {100, 30, 7, 200}},
    {UnitName::Carrier, {100, 16, 5, 175}},

    // --- Air ---
    {UnitName::Airship, {100, 4, 8, 80, 8}},
    {UnitName::Fighter, {100, 12, 6, 100, 6}},
    {UnitName::JetFighter, {100, 24, 10, 150, 10}},
    {UnitName::Bomber, {100, 16, 8, 140, 8}},
    {UnitName::StealthBomber, {100, 20, 12, 200, 12}},

    // --- Missile ---
    {UnitName::GuidedMissile, {100, 40, 1, 60, 4}},
    {UnitName::TacticalNuke, {100, 0, 1, 250, 4}},
    {UnitName::ICBM, {100, 0, 1, 500, 999}},

    // --- Recon ---
    {UnitName::Scout, {100, 1, 2, 15}},
    {UnitName::Explorer, {100, 4, 2, 40}}};

const std::map<UnitName, UnitType> UNIT_TYPE = {
    // --- Civil ---
    {UnitName::Settler, UnitType::Civil},
    {UnitName::Worker, UnitType::Civil},
    {UnitName::WorkBoat, UnitType::Civil},

    // --- Melee ---
    {UnitName::Warrior, UnitType::Melee},
    {UnitName::Swordsman, UnitType::Melee},
    {UnitName::Axeman, UnitType::Melee},
    {UnitName::Maceman, UnitType::Melee},
    {UnitName::Pikeman, UnitType::Melee},

    // --- Gunpowder ---
    {UnitName::Musketman, UnitType::Gunpowder},
    {UnitName::Rifleman, UnitType::Gunpowder},
    {UnitName::Grenadier, UnitType::Gunpowder},
    {UnitName::AntiTank, UnitType::Gunpowder},
    {UnitName::Infantry, UnitType::Gunpowder},
    {UnitName::SAMInfantry, UnitType::Gunpowder},
    {UnitName::Marine, UnitType::Gunpowder},
    {UnitName::NavySEAL, UnitType::Gunpowder},
    {UnitName::Paratrooper, UnitType::Gunpowder},
    {UnitName::MechanizedInfantry, UnitType::Gunpowder},

    // --- Archery ---
    {UnitName::Archer, UnitType::Archery},
    {UnitName::Longbowman, UnitType::Archery},
    {UnitName::Crossbowman, UnitType::Archery},

    // --- Mounted ---
    {UnitName::Chariot, UnitType::Mounted},
    {UnitName::HorseArcher, UnitType::Mounted},
    {UnitName::Cuirassier, UnitType::Mounted},
    {UnitName::Cavalry, UnitType::Mounted},
    {UnitName::WarElephant, UnitType::Mounted},
    {UnitName::BallistaElephant, UnitType::Mounted},

    // --- Armored & Helicopter ---
    {UnitName::Tank, UnitType::Armored},
    {UnitName::ModernArmor, UnitType::Armored},
    {UnitName::Gunship, UnitType::Helicopter},
    {UnitName::MobileSAM, UnitType::Armored},

    // --- Siege ---
    {UnitName::Catapult, UnitType::Siege},
    {UnitName::Trebuchet, UnitType::Siege},
    {UnitName::Cannon, UnitType::Siege},
    {UnitName::MachineGun, UnitType::Siege},
    {UnitName::Artillery, UnitType::Siege},
    {UnitName::MobileArtillery, UnitType::Siege},

    // --- Naval ---
    {UnitName::Galley, UnitType::Naval},
    {UnitName::Trireme, UnitType::Naval},
    {UnitName::Caravel, UnitType::Naval},
    {UnitName::Galleon, UnitType::Naval},
    {UnitName::Privateer, UnitType::Naval},
    {UnitName::Frigate, UnitType::Naval},
    {UnitName::ShipOfTheLine, UnitType::Naval},
    {UnitName::Ironclad, UnitType::Naval},
    {UnitName::Transport, UnitType::Naval},
    {UnitName::Destroyer, UnitType::Naval},
    {UnitName::Battleship, UnitType::Naval},
    {UnitName::MissileCruiser, UnitType::Naval},
    {UnitName::StealthDestroyer, UnitType::Naval},
    {UnitName::Submarine, UnitType::Naval},
    {UnitName::AttackSubmarine, UnitType::Naval},
    {UnitName::Carrier, UnitType::Naval},

    // --- Air ---
    {UnitName::Airship, UnitType::Air},
    {UnitName::Fighter, UnitType::Air},
    {UnitName::JetFighter, UnitType::Air},
    {UnitName::Bomber, UnitType::Air},
    {UnitName::StealthBomber, UnitType::Air},

    // --- Missile ---
    {UnitName::GuidedMissile, UnitType::Missile},
    {UnitName::TacticalNuke, UnitType::Missile},
    {UnitName::ICBM, UnitType::Missile},

    // --- Recon ---
    {UnitName::Scout, UnitType::Recon},
    {UnitName::Explorer, UnitType::Recon}};

const std::map<std::string, UnitName> UNIT_STRING_NAME = {
    // Civil
    {"Settler", UnitName::Settler},
    {"Worker", UnitName::Worker},
    {"WorkBoat", UnitName::WorkBoat},

    // Melee
    {"Warrior", UnitName::Warrior},
    {"Swordsman", UnitName::Swordsman},
    {"Axeman", UnitName::Axeman},
    {"Maceman", UnitName::Maceman},
    {"Pikeman", UnitName::Pikeman},

    // Gunpowder
    {"Musketman", UnitName::Musketman},
    {"Rifleman", UnitName::Rifleman},
    {"Grenadier", UnitName::Grenadier},
    {"AntiTank", UnitName::AntiTank},
    {"Infantry", UnitName::Infantry},
    {"SAMInfantry", UnitName::SAMInfantry},
    {"Marine", UnitName::Marine},
    {"NavySEAL", UnitName::NavySEAL},
    {"Paratrooper", UnitName::Paratrooper},
    {"MechanizedInfantry", UnitName::MechanizedInfantry},

    // Archery
    {"Archer", UnitName::Archer},
    {"Longbowman", UnitName::Longbowman},
    {"Crossbowman", UnitName::Crossbowman},

    // Mounted
    {"Chariot", UnitName::Chariot},
    {"HorseArcher", UnitName::HorseArcher},
    {"Cuirassier", UnitName::Cuirassier},
    {"Cavalry", UnitName::Cavalry},
    {"WarElephant", UnitName::WarElephant},
    {"BallistaElephant", UnitName::BallistaElephant},

    // Armored
    {"Tank", UnitName::Tank},
    {"ModernArmor", UnitName::ModernArmor},
    {"Gunship", UnitName::Gunship},
    {"MobileSAM", UnitName::MobileSAM},

    // Siege
    {"Catapult", UnitName::Catapult},
    {"Trebuchet", UnitName::Trebuchet},
    {"Cannon", UnitName::Cannon},
    {"MachineGun", UnitName::MachineGun},
    {"Artillery", UnitName::Artillery},
    {"MobileArtillery", UnitName::MobileArtillery},

    // Naval
    {"Galley", UnitName::Galley},
    {"Trireme", UnitName::Trireme},
    {"Caravel", UnitName::Caravel},
    {"Galleon", UnitName::Galleon},
    {"Privateer", UnitName::Privateer},
    {"Frigate", UnitName::Frigate},
    {"ShipOfTheLine", UnitName::ShipOfTheLine},
    {"Ironclad", UnitName::Ironclad},
    {"Transport", UnitName::Transport},
    {"Destroyer", UnitName::Destroyer},
    {"Battleship", UnitName::Battleship},
    {"MissileCruiser", UnitName::MissileCruiser},
    {"StealthDestroyer", UnitName::StealthDestroyer},
    {"Submarine", UnitName::Submarine},
    {"AttackSubmarine", UnitName::AttackSubmarine},
    {"Carrier", UnitName::Carrier},

    // Air
    {"Airship", UnitName::Airship},
    {"Fighter", UnitName::Fighter},
    {"JetFighter", UnitName::JetFighter},
    {"Bomber", UnitName::Bomber},
    {"StealthBomber", UnitName::StealthBomber},

    // Missile
    {"GuidedMissile", UnitName::GuidedMissile},
    {"TacticalNuke", UnitName::TacticalNuke},
    {"ICBM", UnitName::ICBM},

    // Recon
    {"Scout", UnitName::Scout},
    {"Explorer", UnitName::Explorer}};

const std::map<UnitName, PowerBonus> UNIT_POWER_BONUS = {
    {UnitName::Settler, {{}, {}, {}, {}}},
    {UnitName::Worker, {{}, {}, {}, {}}},
    {UnitName::WorkBoat, {{}, {}, {}, {}}},

    {UnitName::Warrior, {{}, {}, {}, {0.0, 0.25}}},
    {UnitName::Axeman, {{{UnitType::Melee, 0.5}}, {}, {}, {0.0, 0.0}}},
    {UnitName::Swordsman, {{}, {}, {}, {0.10, 0.0}}},
    {UnitName::Pikeman, {{{UnitType::Mounted, 1.0}}, {}, {}, {0.0, 0.0}}},
    {UnitName::Maceman, {{{UnitType::Melee, 0.5}}, {}, {}, {0.0, 0.0}}},

    {UnitName::Archer, {{}, {}, {{TerrainElevation::Hill, 0.25}}, {0.0, 0.50}}},
    {UnitName::Longbowman,
     {{}, {}, {{TerrainElevation::Hill, 0.25}}, {0.0, 0.50}}},
    {UnitName::Crossbowman, {{{UnitType::Melee, 0.5}}, {}, {}, {0.0, 0.0}}},

    {UnitName::Musketman, {{}, {}, {}, {0.0, 0.0}}},
    {UnitName::Grenadier, {{}, {{UnitName::Rifleman, 0.5}}, {}, {0.0, 0.0}}},
    {UnitName::Rifleman, {{{UnitType::Mounted, 0.25}}, {}, {}, {0.0, 0.0}}},
    {UnitName::AntiTank, {{{UnitType::Armored, 1.0}}, {}, {}, {0.0, 0.0}}},
    {UnitName::MachineGun, {{{UnitType::Gunpowder, 0.5}}, {}, {}, {0.0, 0.0}}},
    {UnitName::SAMInfantry,
     {{{UnitType::Helicopter, 0.75}}, {}, {}, {0.0, 0.0}}},
    {UnitName::Infantry, {{{UnitType::Gunpowder, 0.25}}, {}, {}, {0.0, 0.0}}},
    {UnitName::MobileSAM, {{{UnitType::Helicopter, 0.50}}, {}, {}, {0.0, 0.0}}},
    {UnitName::Marine,
     {{{UnitType::Siege, 0.50}},
      {{UnitName::MachineGun, 0.5}},
      {},
      {0.0, 0.0}}},
    {UnitName::Paratrooper, {{}, {}, {}, {0.0, 0.0}}},
    {UnitName::MechanizedInfantry, {{}, {}, {}, {0.0, 0.0}}},

    {UnitName::Chariot, {{}, {{UnitName::Axeman, 1.0}}, {}, {0.0, 0.0}}},
    {UnitName::HorseArcher, {{}, {}, {}, {0.0, 0.0}}},
    {UnitName::WarElephant, {{{UnitType::Mounted, 0.5}}, {}, {}, {0.0, 0.0}}},
    {UnitName::Cuirassier, {{}, {}, {}, {0.0, 0.0}}},
    {UnitName::Cavalry, {{}, {{UnitName::Cannon, 0.5}}, {}, {0.0, 0.0}}},

    {UnitName::Gunship, {{{UnitType::Armored, 1.0}}, {}, {}, {0.0, 0.0}}},

    {UnitName::Catapult, {{}, {}, {}, {0.0, 0.0}}},
    {UnitName::Trebuchet, {{}, {}, {}, {1.0, 0.0}}},
    {UnitName::Cannon, {{}, {}, {}, {0.0, 0.0}}},
    {UnitName::Artillery, {{{UnitType::Siege, 0.5}}, {}, {}, {0.0, 0.0}}},
    {UnitName::MobileArtillery, {{{UnitType::Siege, 0.5}}, {}, {}, {0.0, 0.0}}},

    {UnitName::Tank, {{}, {}, {}, {0.0, 0.0}}},
    {UnitName::ModernArmor, {{}, {}, {}, {0.0, 0.0}}},

    {UnitName::Scout, {{}, {}, {}, {0.0, 0.0}}},
    {UnitName::Explorer, {{}, {}, {}, {0.0, 0.0}}},

    {UnitName::Galley, {{}, {}, {}, {0.0, 0.0}}},
    {UnitName::Trireme, {{}, {{UnitName::Galley, 0.5}}, {}, {0.0, 0.0}}},
    {UnitName::Caravel, {{}, {}, {}, {0.0, 0.0}}},
    {UnitName::Galleon, {{}, {}, {}, {0.0, 0.0}}},
    {UnitName::Privateer, {{}, {}, {}, {0.0, 0.0}}},
    {UnitName::Frigate, {{}, {}, {}, {0.0, 0.0}}},
    {UnitName::ShipOfTheLine, {{}, {{UnitName::Frigate, 0.5}}, {}, {0.0, 0.0}}},
    {UnitName::Ironclad, {{}, {}, {}, {0.0, 0.0}}},
    {UnitName::Transport, {{}, {}, {}, {0.0, 0.0}}},
    {UnitName::Destroyer, {{}, {}, {}, {0.0, 0.0}}},
    {UnitName::Battleship, {{}, {}, {}, {0.0, 0.0}}},
    {UnitName::Submarine, {{}, {}, {}, {0.0, 0.0}}},
    {UnitName::AttackSubmarine,
     {{}, {{UnitName::Submarine, 0.5}}, {}, {0.0, 0.0}}},
    {UnitName::MissileCruiser, {{}, {}, {}, {0.0, 0.0}}},
    {UnitName::StealthDestroyer, {{}, {}, {}, {0.0, 0.0}}},
    {UnitName::Carrier, {{}, {}, {}, {0.0, 0.0}}},

    {UnitName::Airship, {{}, {}, {}, {0.0, 0.0}}},
    {UnitName::Fighter, {{}, {}, {}, {0.0, 0.0}}},
    {UnitName::JetFighter, {{}, {}, {}, {0.0, 0.0}}},
    {UnitName::Bomber, {{{UnitType::Naval, -0.5}}, {}, {}, {0.0, 0.0}}},
    {UnitName::StealthBomber, {{{UnitType::Naval, -0.5}}, {}, {}, {0.0, 0.0}}},

    {UnitName::GuidedMissile, {{}, {}, {}, {0.0, 0.0}}},
    {UnitName::TacticalNuke, {{}, {}, {}, {0.0, 0.0}}},
    {UnitName::ICBM, {{}, {}, {}, {0.0, 0.0}}},
};

const std::map<UnitName, UnitRequired> UNIT_TECHNOLOGY = {
    {UnitName::Airship, {{TechnologyName::Physics}, {}}},
    {UnitName::Settler, {{}, {}}},
    {UnitName::Worker, {{}, {}}},
    {UnitName::WorkBoat, {{}, {}}},
    {UnitName::Warrior, {{}, {}}},
    {UnitName::Swordsman,
     {{TechnologyName::IronWorking}, {ResourceName::Iron}}},
    {UnitName::Axeman,
     {{TechnologyName::BronzeWorking}, {ResourceName::Copper}}},
    {UnitName::Maceman,
     {{TechnologyName::CivilService, TechnologyName::Machinery},
      {ResourceName::Iron}}},
    {UnitName::Pikeman, {{TechnologyName::Engineering}, {ResourceName::Iron}}},
    {UnitName::Musketman, {{TechnologyName::Gunpowder}, {}}},
    {UnitName::Rifleman, {{TechnologyName::Rifling}, {}}},
    {UnitName::Grenadier, {{TechnologyName::MilitaryScience}, {}}},
    {UnitName::AntiTank, {{TechnologyName::Artillery}, {}}},
    {UnitName::Infantry,
     {{TechnologyName::AssemblyLine, TechnologyName::Rifling}, {}}},
    {UnitName::SAMInfantry, {{TechnologyName::Rocketry}, {}}},
    {UnitName::Marine,
     {{TechnologyName::Industrialism, TechnologyName::Rifling}, {}}},
    {UnitName::NavySEAL,
     {{TechnologyName::Industrialism, TechnologyName::Rifling}, {}}},
    {UnitName::Paratrooper,
     {{TechnologyName::Fascism, TechnologyName::Rifling,
       TechnologyName::Flight},
      {}}},
    {UnitName::MechanizedInfantry,
     {{TechnologyName::Robotics, TechnologyName::Rifling}, {}}},
    {UnitName::Archer, {{TechnologyName::Archery}, {}}},
    {UnitName::Longbowman, {{TechnologyName::Feudalism}, {}}},
    {UnitName::Crossbowman,
     {{TechnologyName::Machinery, TechnologyName::Archery},
      {ResourceName::Iron}}},
    {UnitName::Chariot, {{TechnologyName::TheWheel}, {ResourceName::Horse}}},
    {UnitName::HorseArcher,
     {{TechnologyName::HorsebackRiding, TechnologyName::Archery},
      {ResourceName::Horse}}},
    {UnitName::Cuirassier,
     {{TechnologyName::MilitaryTradition, TechnologyName::Gunpowder,
       TechnologyName::HorsebackRiding},
      {ResourceName::Horse, ResourceName::Iron}}},
    {UnitName::Cavalry,
     {{TechnologyName::MilitaryTradition, TechnologyName::Rifling,
       TechnologyName::HorsebackRiding},
      {ResourceName::Horse}}},
    {UnitName::WarElephant,
     {{TechnologyName::Construction, TechnologyName::HorsebackRiding},
      {ResourceName::Ivory}}},
    {UnitName::BallistaElephant,
     {{TechnologyName::Construction, TechnologyName::HorsebackRiding},
      {ResourceName::Ivory}}},
    {UnitName::Tank,
     {{TechnologyName::Industrialism, TechnologyName::Rifling},
      {ResourceName::Oil}}},
    {UnitName::ModernArmor,
     {{TechnologyName::Composites, TechnologyName::Computers},
      {ResourceName::Oil, ResourceName::Aluminium}}},
    {UnitName::Gunship,
     {{TechnologyName::AdvancedFlight}, {ResourceName::Oil}}},
    {UnitName::MobileSAM, {{TechnologyName::Laser}, {ResourceName::Oil}}},
    {UnitName::Catapult, {{TechnologyName::Construction}, {}}},
    {UnitName::Trebuchet, {{TechnologyName::Engineering}, {}}},
    {UnitName::Cannon, {{TechnologyName::Steel}, {ResourceName::Iron}}},
    {UnitName::MachineGun, {{TechnologyName::Railroad}, {}}},
    {UnitName::Artillery, {{TechnologyName::Artillery}, {}}},
    {UnitName::MobileArtillery,
     {{TechnologyName::Laser, TechnologyName::Artillery}, {ResourceName::Oil}}},
    {UnitName::Galley, {{TechnologyName::Sailing}, {}}},
    {UnitName::Trireme,
     {{TechnologyName::MetalCasting, TechnologyName::Sailing}, {}}},
    {UnitName::Caravel, {{TechnologyName::Optics}, {}}},
    {UnitName::Galleon, {{TechnologyName::Astronomy}, {}}},
    {UnitName::Privateer,
     {{TechnologyName::Chemistry, TechnologyName::Astronomy},
      {ResourceName::Copper}}},
    {UnitName::Frigate,
     {{TechnologyName::Chemistry, TechnologyName::Astronomy},
      {ResourceName::Iron}}},
    {UnitName::ShipOfTheLine,
     {{TechnologyName::MilitaryScience, TechnologyName::Astronomy},
      {ResourceName::Iron}}},
    {UnitName::Ironclad,
     {{TechnologyName::Steel, TechnologyName::SteamPower},
      {ResourceName::Iron, ResourceName::Coal}}},
    {UnitName::Transport, {{TechnologyName::Combustion}, {ResourceName::Oil}}},
    {UnitName::Destroyer, {{TechnologyName::Combustion}, {ResourceName::Oil}}},
    {UnitName::Battleship,
     {{TechnologyName::Industrialism}, {ResourceName::Oil}}},
    {UnitName::MissileCruiser,
     {{TechnologyName::Robotics}, {ResourceName::Oil}}},
    {UnitName::StealthDestroyer,
     {{TechnologyName::Stealth, TechnologyName::Robotics},
      {ResourceName::Oil, ResourceName::Uranium}}},
    {UnitName::Submarine, {{TechnologyName::Radio}, {ResourceName::Uranium}}},
    {UnitName::AttackSubmarine,
     {{TechnologyName::Rocketry, TechnologyName::Radio,
       TechnologyName::Combustion},
      {ResourceName::Uranium}}},
    {UnitName::Carrier, {{TechnologyName::Flight}, {ResourceName::Oil}}},
    {UnitName::Airship, {{TechnologyName::AdvancedFlight}, {}}},
    {UnitName::Fighter, {{TechnologyName::Flight}, {ResourceName::Oil}}},
    {UnitName::JetFighter,
     {{TechnologyName::AdvancedFlight},
      {ResourceName::Oil, ResourceName::Aluminium}}},
    {UnitName::Bomber,
     {{TechnologyName::Radio, TechnologyName::Flight}, {ResourceName::Oil}}},
    {UnitName::StealthBomber,
     {{TechnologyName::Stealth, TechnologyName::Robotics},
      {ResourceName::Oil, ResourceName::Aluminium}}},
    {UnitName::GuidedMissile,
     {{TechnologyName::Rocketry, TechnologyName::Radio}, {}}},
    {UnitName::TacticalNuke,
     {{TechnologyName::Fission, TechnologyName::Rocketry},
      {ResourceName::Uranium}}},
    {UnitName::ICBM,
     {{TechnologyName::Fission, TechnologyName::Rocketry},
      {ResourceName::Uranium}}},
    {UnitName::Scout, {{TechnologyName::Hunting}, {}}},
    {UnitName::Explorer, {{TechnologyName::Compass}, {}}}};